version: '3.4'

services:
  webapp:
    image: openia_net-web    
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5208:8080"